### ISSUE TITLE
연차..시면서

### ISSUE THREAD

**Issue by YunHye-Choi** [dboostudio/jpa-ref#1]
왜 .그럭 게. 열심이신.거죠?
부하.직원.으로서. 보기 .불편.하네요.부하.직원.으로서. 보기 .불편.하네요.부하.직원.으로서. 보기 .불편.하네요.부하.직원.으로서. 보기 .불편.하네요.부하.직원.으로서. 보기 .불편.하네요.부하.직원.으로서. 보기 .불편.하네요.부하.직원.으로서. 보기 .불편.하네요.부하.직원.으로서. 보기 .불편.하네요.부하.직원.으로서. 보기 .불편.하네요.부하.직원.으로서. 보기 .불편.하네요.부하.직원.으로서. 보기 .불편.하네요.부하.직원.으로서. 보기 .불편.하네요.부하.직원.으로서. 보기 .불편.하네요.부하.직원.으로서. 보기 .불편.하네요.부하.직원.으로서. 보기 .불편.하네요.부하.직원.으로서. 보기 .불편.하네요.부하.직원.으로서. 보기 .불편.하네요.부하.직원.으로서. 보기 .불편.하네요.부하.직원.으로서. 보기 .불편.하네요.부하.직원.으로서. 보기 .불편.하네요.부하.직원.으로서. 보기 .불편.하네요.부하.직원.으로서. 보기 .불편.하네요.부하.직원.으로서. 보기 .불편.하네요.부하.직원.으로서. 보기 .불편.하네요.부하.직원.으로서. 보기 .불편.하네요.부하.직원.으로서. 보기 .불편.하네요.부하.직원.으로서. 보기 .불편.하네요.부하.직원.으로서. 보기 .불편.하네요.부하.직원.으로서. 보기 .불편.하네요.부하.직원.으로서. 보기 .불편.하네요.부하.직원.으로서. 보기 .불편.하네요.부하.직원.으로서. 보기 .불편.하네요.

**Comment by dboostudio** [comment]
원래 쉬는날엔 취미로 공부해야져 이슈 닫습니다
